services:
  ingesta_catalogo:
    build: ./ingesta-catalogo
    image: villabos/ingesta-catalogo:v1
    container_name: ingesta_catalogo
    env_file: .env
    # Se ejecuta y termina (no usar restart: always porque es un proceso de extracción)

  ingesta_comunity:
    build: ./ingesta-comunity
    image: villabos/ingesta-comunity:v1
    container_name: ingesta_comunity
    env_file: .env

  ingesta_iteraction:
    build: ./ingesta-iteraction
    image: villabos/ingesta-iteraction:v1
    container_name: ingesta_iteraction
    env_file: .env
